spring.config.activate.on-profile=dev

spring.security.oauth2.client.registration.github.redirect-uri=http://localhost:8080/browser-dom/login/oauth2/code/github

spring.cloud.azure.keyvault.secret.profile.tenant-id=f65dc3b5-9ded-4b51-86ba-fc1e3adc29d4
spring.cloud.azure.keyvault.secret.credential.client-id=125e6e88-574c-4c49-9f6f-4f5e49433615
spring.cloud.azure.keyvault.secret.credential.client-secret=ed58Q~AAJn62CircyKoImmeroui1lRAVAfFD2ckP